### ISSUE TITLE
Can't seem to connect But I can use jaydebeapi.connect perfectly fine

### ISSUE THREAD

**Issue by martyzz1** [bwadle/sqlalchemy-jdbc-generic#1]
I'm trying to use this generic driver to connect to mongo's new federated database so I can run SQL commands.

I can successfully connect using the foillowing command

```
  driver_class = "com.mongodb.jdbc.MongoDriver"
  driver_path = "/usr/local/airflow/include/mongodb-jdbc-2.0.3.jar"
  credentials = ["username", "unescaped_password"]
  connection_url = (
    "jdbc:mongodb://federateddatabaseinstance***-***.*.***.mongodb.net/"
    "databasename?ssl=true&authSource=admin"
  )
  conn = jaydebeapi.connect(
    driver_class,
    connection_url,
    credentials,
    driver_path,
  )
```

No port is specified, but I think its defaulting to 27017 

When I try to connect using this project I get timeouts

```
  eng_url = URL.create(
      drivername="sqlajdbc",
      host="federateddatabaseinstance***-***.*.***.mongodb.net/",
      username=quote_plus("unescaped_username"),
      password=quote_plus("unescaped_password"),
      query={"ssl": "true", "authSource":"admin", "_class": driver_class, "_driver": "mongodb", "_jars": driver_path, "db": "databasename"})
```

I get 
`java.sql.SQLTimeoutException: java.sql.SQLTimeoutException: Couldn't connect due to a timeout. Please check your hostname and port. If necessary, set a longer connection timeout in the MongoDB URI.`

**Comment by bwadle** [comment]
I would recommend trying to refer to the database either within the `host` or `database` argument.  Instead of using the `query.db` query string argument if you want to mirror what your first example uses.

```python
eng_url = URL.create(
    drivername="sqlajdbc",
    host="federateddatabaseinstance***-***.*.***.mongodb.net/databasename",
    ...
)
```
or
```python
eng_url = URL.create(
    drivername="sqlajdbc",
    host="federateddatabaseinstance***-***.*.***.mongodb.net",
    database="databasename",
    ...
)
```

**Comment by bwadle** [comment]
Closing Issue as Complete
